### ISSUE TITLE
Any idea for adding additional users 

### ISSUE THREAD

**Issue by pr13260** [tuhinpal/Firecdn#1]
like in my Project i want to add some more people ie my workmate 
but i don't want to share him my email and password
can i create a new user account in firebase and give it's acess to him ?

**Comment by pr13260** [comment]
Okay my bad
Found that You can create infinite number of users then repeat rules lines and change uid It works like Charm 
Great Work Man

**Comment by tuhinpal** [comment]
Thanks!
